// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgyxcanbcokkfhbrkrtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneXhjYW5iY29ra2ZoYnJrcnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzU5NTIsImV4cCI6MjA1OTM1MTk1Mn0.da4Nw3PLssJgjkROYNsb-Spnw05bARjfbtNMXPDIB5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);